--- Gameplay options tree

local page_gameplay_general = options_modded_exes_gameplay_general.PAGE
local page_aim = options_modded_exes_aim.PAGE
local page_3d_ballistics = options_modded_exes_3d_ballistics.PAGE
local page_weapons = options_modded_exes_weapons.PAGE
local page_stalkers = options_modded_exes_stalkers.PAGE
local page_monsters = options_modded_exes_monsters.PAGE
local page_bodycam = options_modded_exes_bodycam.PAGE
local page_bodycam_recoil = options_modded_exes_bodycam_recoil.PAGE
local page_bodycam_sway = options_modded_exes_bodycam_sway.PAGE

-- Import smart constructors
options_builder.import_into(this)

-- Options group
GROUP = group {
	{ id = "gameplay" },
	page_gameplay_general,
	page_aim,
	page_3d_ballistics,
	page_weapons,
	page_bodycam,
	page_bodycam_recoil,
	page_bodycam_sway,
	page_stalkers,
	page_monsters,
}